from apify_client import ApifyClient

# Initialize the ApifyClient with your API token
client = ApifyClient("apify_api_wwbSwHW0oPRzU14HT1ZLxZwNQQIBd22ly8br")

# Prepare the Actor input
run_input = {
    "getEmails": True,
    "searchUrl":"app.apollo.io/#/people?finderViewId=5b6dfc5a73f47568b2e5f11c&page=1&organizationIds[]=5a9e0a22a6da98d946718475&prospectedByCurrentTeam[]=no",
    "startPage": 1,
    "count": 100,
    "minDelay": 5,
    "maxDelay": 15,
     "cookie":[
{
    "domain": ".apollo.io",
    "expirationDate": 1702538994,
    "hostOnly": False,
    "httpOnly": False,
    "name": "__hssc",
    "path": "/",
    "sameSite": "lax",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "21978340.4.1702536940724",
    "id": 1
},
{
    "domain": ".apollo.io",
    "hostOnly": False,
    "httpOnly": False,
    "name": "__hssrc",
    "path": "/",
    "sameSite": "lax",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "1",
    "id": 2
},
{
    "domain": ".apollo.io",
    "expirationDate": 1718089194,
    "hostOnly": False,
    "httpOnly": False,
    "name": "__hstc",
    "path": "/",
    "sameSite": "lax",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "21978340.77cae0230d29d642b0a1bf322f399499.1700631269728.1702452725626.1702536940724.11",
    "id": 3
},
{
    "domain": ".apollo.io",
    "expirationDate": 1732167277,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_cioanonid",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "0e46a4c1-fbeb-5ee3-b7fc-3ab725e85e4e",
    "id": 4
},
{
    "domain": ".apollo.io",
    "expirationDate": 1734073202,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_cioid",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "6502aa769b918600ec701588",
    "id": 5
},
{
    "domain": ".apollo.io",
    "expirationDate": 1710228725,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_fbp",
    "path": "/",
    "sameSite": "lax",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "fb.1.1700631268042.285418479",
    "id": 6
},
{
    "domain": ".apollo.io",
    "expirationDate": 1737012725.549832,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_ga",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "GA1.1.607734230.1700631137",
    "id": 7
},
{
    "domain": ".apollo.io",
    "expirationDate": 1735365681.088454,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_ga_2KJN2H89XE",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "GS1.1.1700805676.1.0.1700805681.55.0.0",
    "id": 8
},
{
    "domain": ".apollo.io",
    "expirationDate": 1737012725.874794,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_ga_76XXTC73SP",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "GS1.1.1702452725.9.0.1702452725.60.0.0",
    "id": 9
},
{
    "domain": ".apollo.io",
    "expirationDate": 1735191167.842959,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_ga_CBPPE9HPBE",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "GS1.1.1700631137.1.1.1700631167.0.0.0",
    "id": 10
},
{
    "domain": ".apollo.io",
    "expirationDate": 1708407268,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_gcl_au",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "1.1.194556164.1700631268",
    "id": 11
},
{
    "domain": ".apollo.io",
    "expirationDate": 1732167137,
    "hostOnly": False,
    "httpOnly": False,
    "name": "amp_122a93",
    "path": "/",
    "sameSite": "lax",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "k8lYTLPu9djFRi6OibEtJv...1hfqo7jgn.1hfqo7jgq.0.1.1",
    "id": 12
},
{
    "domain": ".apollo.io",
    "expirationDate": 1737097203.558108,
    "hostOnly": False,
    "httpOnly": False,
    "name": "amplitude_id_122a93c7d9753d2fe678deffe8fac4cfapollo.io",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "eyJkZXZpY2VJZCI6ImVkYTkxZGUzLWU1ZDgtNGYzZS1iNmViLTM5NjU5ODI0MWRmNFIiLCJ1c2VySWQiOiI2NTAyYWE3NjliOTE4NjAwZWM3MDE1ODgiLCJvcHRPdXQiOnRydWUsInNlc3Npb25JZCI6MTcwMjUzNjkzODgyOSwibGFzdEV2ZW50VGltZSI6MTcwMjUzNzE5MzY2NCwiZXZlbnRJZCI6MTQwLCJpZGVudGlmeUlkIjoxMTcsInNlcXVlbmNlTnVtYmVyIjoyNTd9",
    "id": 13
},
{
    "domain": ".apollo.io",
    "expirationDate": 1708581676,
    "hostOnly": False,
    "httpOnly": False,
    "name": "growSumoPartnerKey",
    "path": "/",
    "sameSite": "lax",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "damianweathers8641",
    "id": 14
},
{
    "domain": ".apollo.io",
    "expirationDate": 1718089194,
    "hostOnly": False,
    "httpOnly": False,
    "name": "hubspotutk",
    "path": "/",
    "sameSite": "lax",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "77cae0230d29d642b0a1bf322f399499",
    "id": 15
},
{
    "domain": ".apollo.io",
    "expirationDate": 1725867203,
    "hostOnly": False,
    "httpOnly": False,
    "name": "intercom-device-id-dyws6i9m",
    "path": "/",
    "sameSite": "lax",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "011e8bfc-3aec-4c65-b271-1884dea03f03",
    "id": 16
},
{
    "domain": ".apollo.io",
    "expirationDate": 1703142003,
    "hostOnly": False,
    "httpOnly": False,
    "name": "intercom-session-dyws6i9m",
    "path": "/",
    "sameSite": "lax",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "eFc3UUkwdjV1dzlIZEJqS0g4UlhON1N4VUVhN2d5Z3E4d2huSGQzbk9sNGx1SEZrSnBBMU5BeVA1ZFVHWC80VC0tbGFvYWxpVzF2bUlVMm1jcWJjYlNVQT09--6c9badc267edb0ff7632c8ffab9b0bbda638a15e",
    "id": 17
},
{
    "domain": ".apollo.io",
    "expirationDate": 1735191265.606227,
    "hostOnly": False,
    "httpOnly": False,
    "name": "mutiny.user.token",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "fdb05f87-ded8-41ca-ba62-1d1c9668fbdb",
    "id": 18
},
{
    "domain": ".apollo.io",
    "expirationDate": 1708581676,
    "hostOnly": False,
    "httpOnly": False,
    "name": "ps_mode",
    "path": "/",
    "sameSite": "lax",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "trackingV1",
    "id": 19
},
{
    "domain": ".apollo.io",
    "expirationDate": 1708581676,
    "hostOnly": False,
    "httpOnly": False,
    "name": "ps_partner_key",
    "path": "/",
    "sameSite": "lax",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "damianweathers8641",
    "id": 20
},
{
    "domain": ".apollo.io",
    "expirationDate": 1705215592.806148,
    "hostOnly": False,
    "httpOnly": False,
    "name": "remember_token_leadgenie_v2",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": True,
    "session": False,
    "storeId": "0",
    "value": "eyJfcmFpbHMiOnsibWVzc2FnZSI6IklqWTFNREpoWVRjMk9XSTVNVGcyTURCbFl6Y3dNVFU0T0Y5bU9EbGpZak5oWkRBd05HUmpZMk15TURJNU16VXpZMk00Wm1Nek9ESmhZU0k9IiwiZXhwIjoiMjAyNC0wMS0xNFQwNjo1OTo1My40NjBaIiwicHVyIjoiY29va2llLnJlbWVtYmVyX3Rva2VuX2xlYWRnZW5pZV92MiJ9fQ%3D%3D--0e9aa46debb37e6a011c1138f787e16a14e31efb",
    "id": 21
},
{
    "domain": ".apollo.io",
    "expirationDate": 1705815266,
    "hostOnly": False,
    "httpOnly": False,
    "name": "zp__gspk",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "ZGFtaWFud2VhdGhlcnM4NjQx",
    "id": 22
},
{
    "domain": ".apollo.io",
    "expirationDate": 1705815266,
    "hostOnly": False,
    "httpOnly": False,
    "name": "zp__gsxid",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "FweNsaBNUKvA",
    "id": 23
},
{
    "domain": ".apollo.io",
    "expirationDate": 1705815266,
    "hostOnly": False,
    "httpOnly": False,
    "name": "zp__initial_referrer",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "https://www.google.com/",
    "id": 24
},
{
    "domain": ".apollo.io",
    "expirationDate": 1705815266,
    "hostOnly": False,
    "httpOnly": False,
    "name": "zp__initial_utm_campaign",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "marketplace_damianweathers8641",
    "id": 25
},
{
    "domain": ".apollo.io",
    "expirationDate": 1705815266,
    "hostOnly": False,
    "httpOnly": False,
    "name": "zp__initial_utm_gspartnerkey",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "damianweathers8641",
    "id": 26
},
{
    "domain": ".apollo.io",
    "expirationDate": 1705815266,
    "hostOnly": False,
    "httpOnly": False,
    "name": "zp__initial_utm_medium",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "partner",
    "id": 27
},
{
    "domain": ".apollo.io",
    "expirationDate": 1705815266,
    "hostOnly": False,
    "httpOnly": False,
    "name": "zp__initial_utm_source",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "affiliates_partnerstack",
    "id": 28
},
{
    "domain": ".apollo.io",
    "expirationDate": 1705989676,
    "hostOnly": False,
    "httpOnly": False,
    "name": "zp__utm_campaign",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "Discovery%20Company%20Page%20-%20General",
    "id": 29
},
{
    "domain": ".apollo.io",
    "expirationDate": 1705815266,
    "hostOnly": False,
    "httpOnly": False,
    "name": "zp__utm_gspartnerkey",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "damianweathers8641",
    "id": 30
},
{
    "domain": ".apollo.io",
    "expirationDate": 1705989676,
    "hostOnly": False,
    "httpOnly": False,
    "name": "zp__utm_medium",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "Discovery",
    "id": 31
},
{
    "domain": ".apollo.io",
    "expirationDate": 1705989676,
    "hostOnly": False,
    "httpOnly": False,
    "name": "zp__utm_source",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "Apollo",
    "id": 32
},
{
    "domain": ".apollo.io",
    "hostOnly": False,
    "httpOnly": False,
    "name": "ZP_Pricing_Split_Test_Variant",
    "path": "/",
    "sameSite": "lax",
    "secure": True,
    "session": True,
    "storeId": "0",
    "value": "23Q2_EC_W49",
    "id": 33
},
{
    "domain": ".app.apollo.io",
    "expirationDate": 1734073205,
    "hostOnly": False,
    "httpOnly": False,
    "name": "__stripe_mid",
    "path": "/",
    "sameSite": "strict",
    "secure": True,
    "session": False,
    "storeId": "0",
    "value": "f72a1e1f-59d1-4973-83bd-8d242d8561b38b12c7",
    "id": 34
},
{
    "domain": ".app.apollo.io",
    "expirationDate": 1702539005,
    "hostOnly": False,
    "httpOnly": False,
    "name": "__stripe_sid",
    "path": "/",
    "sameSite": "strict",
    "secure": True,
    "session": False,
    "storeId": "0",
    "value": "7da51ca4-60c4-41bc-b0a6-fa955795b92cff9d88",
    "id": 35
},
{
    "domain": "app.apollo.io",
    "expirationDate": 1702538109,
    "hostOnly": True,
    "httpOnly": False,
    "name": "_dd_s",
    "path": "/",
    "sameSite": "strict",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "rum=0&expire=1702538106971",
    "id": 36
},
{
    "domain": "app.apollo.io",
    "hostOnly": True,
    "httpOnly": True,
    "name": "_leadgenie_session",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": True,
    "session": True,
    "storeId": "0",
    "value": "1BFb%2BOslkoNNI45pu4utzzAaEXIZalTEbkFEcf3v74NP7Odc5ANCwTC1%2B4WgvZk05oVtLP5HznR3j21kvZV5eMOGccVxE9RIXnxJsyntspqIkqKdSa1erAmnZ5dntl3BuqvSncyo1MjydLpoJ6UM96ZOAUuhCbcq%2BPRBEuf6wmKQ%2Fwqo0biy8Wmv09RzJ59UDt7FsNxvZwKWeHY%2Bp21lOMvz3u3ME139e2puYPz3KhcFXJFVW5zA051WJiLXeY2AvnmXL7i2Y4rinkcVvPuHFKo6QZuiIYOHd%2Bk%3D--UpiuM%2Br93qeRVnTh--dNtOxs4vueB2WGLhifsMJA%3D%3D",
    "id": 37
},
{
    "domain": "app.apollo.io",
    "expirationDate": 1702537537.644231,
    "hostOnly": True,
    "httpOnly": True,
    "name": "GCLB",
    "path": "/",
    "sameSite": "unspecified",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "CPnhytbr9qnBtwE",
    "id": 38
},
{
    "domain": "app.apollo.io",
    "hostOnly": True,
    "httpOnly": False,
    "name": "X-CSRF-TOKEN",
    "path": "/",
    "sameSite": "lax",
    "secure": True,
    "session": True,
    "storeId": "0",
    "value": "a65WrNFi5dU6yNLWuoZIEJ5-OiVtOHO2w-Jr970rZnnFoROdd77HPxyNATo3ibzAon39NWR5AelK1JVBRWoIEw",
    "id": 39
}
]
}

# Run the Actor and wait for it to finish
run = client.actor("curious_coder/apollo-io-scraper").call(run_input=run_input)

# Fetch and print Actor results from the run's dataset (if there are any)
for item in client.dataset(run["defaultDatasetId"]).iterate_items():
    print(item['title'])
    print(item['name'])
    # print(item)
#    if(item['title']=='Chair and CEO'):
#     print(item['email'])
#     print(item['name'])

   